### ISSUE TITLE
Web worker compatibility issue

### ISSUE THREAD

**Issue by megazyz** [jsakamoto/BlazorWasmPreRendering.Build#37] opened 2023-09-17 20:48 UTC
Apps with prerendering crash when starting a web worker using the library [SpawnDev.BlazorJS](https://github.com/LostBeard/SpawnDev.BlazorJS), because `BlazorWasmPreRendering.Build` attempts to call the `document.createNodeIterator` function at startup, which is not available in web workers:

```
logging.ts:24 MONO_WASM: Failed to invoke 'afterStarted' on library initializer '../_content/BlazorWasmPreRendering.Build/BlazorWasmPreRendering.Build.lib.module.js': TypeError: n.createNodeIterator is not a function
```

Can be fixed by adding a check before calling `document.createNodeIterator` in the file `BlazorWasmPreRendering.Build.lib.module.js`, for example:

```js
if (typeof document.createNodeIterator !== 'function') return;
```

However I'm not familiar with `BlazorWasmPreRendering.Build`, and I'm not sure if this is the best place to check if we are in a web worker.

**Comment by jsakamoto** [comment] 2023-09-18 03:26
@megazyz Thank you for reporting!
Could you provide me a minimal sample code that can reproduce this issue?
It would be useful for investigating and resolving the issue shorter.

**Comment by megazyz** [comment] 2023-09-18 14:52
Sure, [here](https://github.com/megazyz/Example.PrerenderingWithWorkers) is a minimal sample

**Comment by jsakamoto** [comment] 2023-09-18 23:28
@megazyz 

Thank you for providing the minimal sample! It was really helpful to investigate the problem. Since you provided me the sample, I could reproduce the problem on my side that you reported in this thread (The problem only occurred in dotNET 8). I will be able to fix the "BlazorWasmPreRendering.Build" as you suggested.

Unfortunately, I found another problem when I was publishing (including the pre-rendering process) the app. The publishing process failed with the unhandled exception, "System.TypeLoadException: Generic method or method in generic class is internal call, PInvoke, or is defined in a COM Import class". This problem is based on the essential architecture of the "BlazorWasmPreRendering.Build" that makes the Blazor Wasm app run as a Blazor Server forcibly to generate static pre-rendered contents, and it is conflicted with the requirement of the "SpawnDev.BlazorJS.WebWorkers" that the app must run only inside web browsers. So it's really tough to resolve this new problem. I could not find any workarounds so far.😥

Please let me have a long time to try to resolve this issue. It might need to change the "SpawnDev.BlazorJS.WebWorkers" side.

**Comment by megazyz** [comment] 2023-09-19 22:17
@jsakamoto thank you for looking into this.

As a solution to the problem occuring in the publishing process, I do not use web workers in the Prerendering environment (I use single thread code instead that provide the same output without using web workers), and do not call AddWebWorkerService and AddBlazorJSRuntime in ConfigureServices. I think this is an absolutely acceptable solution to this problem.

I will add checks for prerendering environment to the sample project when I get back to my desk in a few days.

**Comment by megazyz** [comment] 2023-09-20 11:12
I added fallback code for prerendering environment (megazyz/Example.PrerenderingWithWorkers@d34ff18), project publishing now works.

**Comment by jsakamoto** [comment] 2023-09-20 13:04
@megazyz Thank you for your posts.
Fortunately, I could fix the issue that the helper script will crash when it runs in a web worker today. Please check the latest version of the BlazorWasmPreRendering.Build.

- https://www.nuget.org/packages/BlazorWasmPreRendering.Build/3.1.0-preview.4#release-body-tab

And, I implemented yet another fallback implementation, too. You can see my implementation [here](https://github.com/jsakamoto/Example.PrerenderingWithWorkers/commit/469b2cf0c1e157eea811b299320749377e1fe0f0). It will be simpler than [your implementation](https://github.com/megazyz/Example.PrerenderingWithWorkers/commit/d34ff18).

**Comment by megazyz** [comment] 2023-09-21 21:06
@jsakamoto Thank you for the fix, I checked the latest version and it works perfectly for me. Also thank you for the fallback example, your implementation is much cleaner. Somehow I did not take into account that there are no click events during prerendering.

**Closed** 2023-09-21 21:07 UTC
